<?php

namespace CommonBundle\Repository;
use Doctrine\ORM\Query;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll($idParentCategory = null, $status = true)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c.id, c.name')
            ->where('c.status = :status')
            ->setParameter('status', $status)
            ->orderBy('c.order', 'ASC');

        if ($idParentCategory) {
            $qb->andWhere('c.parentCategory = :idParentCategory')
                ->setParameter('idParentCategory', $idParentCategory);
        } else {
            $qb->andWhere($qb->expr()->isNull('c.parentCategory'));
        }

        $query = $qb->getQuery();

        return $query->getResult(Query::HYDRATE_ARRAY);
    }

    public function getAllTree()
    {
        $parents = $this->getAll();
        foreach ($parents as &$parent) {
            $parent['children'] = $this->getAll($parent['id']);
        }

        return $parents;
    }
}
