<?php

namespace CommonBundle\Repository;
use Doctrine\ORM\Query;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll($status = true)
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.status = :status')
            ->setParameter('status', $status)
            ->orderBy('p.name', 'ASC');

        $query = $qb->getQuery();

        return $query->getResult(Query::HYDRATE_ARRAY);
    }

}
