CommonBundle\Entity\Client:
    type: entity
    table: client
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        name:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
        document1:
            type: string
            nullable: false
            length: 14
            options:
                fixed: false
            column: document_1
        document2:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: document_2
        birthData:
            type: date
            nullable: true
            column: birth_data
        genre:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        telephone:
            type: string
            nullable: false
            length: 14
            options:
                fixed: false
        celphone:
            type: string
            nullable: true
            length: 14
            options:
                fixed: false
        postalCode:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
            column: postal_code
        address:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
        adrressComplement:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: adrress_complement
        neighborhood:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        city:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        state:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        newsletter:
            type: boolean
            nullable: false
            options:
                default: '1'
        status:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
