CommonBundle\Entity\OrderStatus:
    type: entity
    table: order_status
    indexes:
        order_id:
            columns:
                - order_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        value:
            type: boolean
            nullable: false
            options:
                comment: '1=Aguardando Pagamento; 2=Aguardando Confirmação; 3=Pagamento Confirmado; 4=Pedido Entregue; 5=Cancelado'
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        order:
            targetEntity: Order
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                order_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
