CommonBundle\Entity\ProductSku:
    type: entity
    table: product_sku
    indexes:
        FK_prod_sku_idProduto:
            columns:
                - product_id
    id:
        sku:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
                default: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        showcase:
            type: boolean
            nullable: false
            options:
                default: '0'
        supplierRef:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: supplier_ref
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
        cost:
            type: float
            nullable: false
            precision: 10
            scale: 0
        weight:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                comment: gramas
        height:
            type: float
            nullable: false
            precision: 10
            scale: 0
        width:
            type: float
            nullable: false
            precision: 10
            scale: 0
        length:
            type: float
            nullable: false
            precision: 10
            scale: 0
        stock:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        stockMin:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: stock_min
        order:
            type: boolean
            nullable: false
        status:
            type: boolean
            nullable: false
            options:
                default: '1'
    manyToOne:
        product:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        attribute:
            targetEntity: VariationAttribute
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: sku
            joinTable:
                name: product_sku_attribute
                joinColumns:
                    -
                        name: sku
                        referencedColumnName: sku
                inverseJoinColumns:
                    -
                        name: attribute_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
