CommonBundle\Entity\ProductSkuImage:
    type: entity
    table: product_sku_image
    indexes:
        FK_prod_sku_img_SKU:
            columns:
                - sku
        FK_prod_sku_img_idImagem:
            columns:
                - image
    id:
        image:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
            id: true
    fields:
        order:
            type: boolean
            nullable: false
            options:
                default: '0'
    oneToOne:
        sku:
            targetEntity: ProductSku
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sku:
                    referencedColumnName: sku
            orphanRemoval: false
    lifecycleCallbacks: {  }
