CommonBundle\Entity\Suppliers:
    type: entity
    table: suppliers
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        status:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
