CommonBundle\Entity\Variation:
    type: entity
    table: variation
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
                default: ''
        label:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
                default: ''
        unique:
            type: boolean
            nullable: false
            options:
                default: '0'
    manyToMany:
        product:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: variation
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
