services:
    filters_extension:
        class: SiteBundle\Extensions\Twig\FiltersExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    api_category:
        class: SiteBundle\Services\Api\Category
        arguments: ['@service_container']

    api_product:
        class: SiteBundle\Services\Api\Product
        arguments: ['@service_container']

    api_recommendation:
        class: SiteBundle\Services\Api\Recommendation
        arguments: ['@service_container']

